version: '3.8'

services:
  # Serviço do Banco de Dados (Postgres)
  postgres_db:
    image: postgres:16-alpine
    container_name: db_englishverse
    restart: always
    environment:
      POSTGRES_DB: db_englishverse
      POSTGRES_USER: neto
      POSTGRES_PASSWORD: englishverse
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  # Serviço do Backend (Spring Boot)
  backend:
    build:
      context: ./backend
    container_name: backend_englishverse
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/db_englishverse
      - SPRING_DATASOURCE_USERNAME=neto
      - SPRING_DATASOURCE_PASSWORD=englishverse
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  # Serviço do Frontend (React + Vite)
  frontend:
    build:
      context: ./frontend
    container_name: frontend_englishverse
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend