version: '3.8'

services:
  # Servi√ßo do Banco de Dados (Postgres)
  postgres_db:
    image: postgres:16-alpine
    container_name: db_englishverse
    restart: always
    environment:
      POSTGRES_DB: db_englishverse
      POSTGRES_USER: neto
      POSTGRES_PASSWORD: englishverse
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data